output/objects/Parcela_Mega__c.object
<CustomObject>
    <label>Parcela do Contrato</label>
    <nameField>
        <label>Parcela</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcelas do Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aberto</fullName>
                </value>
                <value>
                    <fullName>Baixado</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/BarcodeControllerTest.cls
@isTest
private class BarcodeControllerTest {
    
    @TestSetup
    static void setup(){
        
        ObjectBuilderForTests.getNewParcelaMega(true);
    }

    @isTest
    static void testBuildEnqueueJobs() {

        Parcela_Mega__c parcelaMega = [SELECT Id, Status__c, Codigo_de_Barras_Mega__c FROM Parcela_Mega__c LIMIT 1];

        Test.startTest();
        PageReference pageRef = Page.ItauBoletoPDF;
        pageRef.getParameters().put('parcelaMegaId', parcelaMega.Id);
        Test.setCurrentPage(pageRef);
        
        BarcodeController testBarcodeController = new BarcodeController();
        Test.stopTest();
    }
}