output/objects/Parcela_Mega__c.object
<CustomObject>
    <label>Parcela do Contrato</label>
    <nameField>
        <label>Parcela</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcelas do Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aberto</fullName>
                </value>
                <value>
                    <fullName>Baixado</fullName>
                </value>
                <value>
                    <fullName>Inativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/PDFHelperTests.cls
@isTest
private class PDFHelperTests {
    
    @TestSetup
    static void setup(){
        
        ObjectBuilderForTests.getNewParcelaMega(true);
    }

    @isTest
    static void testBuildEnqueueJobs() {

        Parcela_Mega__c parcelaMega = [SELECT Id, Status__c, Codigo_de_Barras_Mega__c FROM Parcela_Mega__c LIMIT 1];

        Boolean isInsert = true;
        List<Parcela_Mega__c> listNew = new List<Parcela_Mega__c>();
        Map<Id, Parcela_Mega__c> mapOldValues = new Map<Id, Parcela_Mega__c>();

        listNew.add(parcelaMega);

        Test.startTest();
        PDFHelper.getInstance().buildEnqueueJobs(isInsert, listNew, mapOldValues);
        Test.stopTest();
    }
}