output/objects/Parcela_Mega__c.object
<CustomObject>
    <label>Parcela do Contrato</label>
    <nameField>
        <label>Parcela</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parcelas do Contrato</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Contrato_Mega__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contrato Mega</label>
        <referenceTo>Contrato_Mega__c</referenceTo>
        <relationshipLabel>Parcelas do Contrato</relationshipLabel>
        <relationshipName>Parcelas_do_Contrato</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/classes/PagamentoAvulsoController.cls
public without sharing class PagamentoAvulsoController {
    @AuraEnabled
    public static List<Parcela_Mega__c> getParcelaByContrato(List<Id> contratosId) {
        return [SELECT Id, Name, Valor__c FROM Parcela_Mega__c WHERE Contrato_Mega__c IN :contratosId];
    }

    @AuraEnabled
    public static List<AggregateResult> getEmpreendimentosByConta(Id contaId){
        try {
            return [
                SELECT
                    Count(Name),
                    Unidade__r.Empreendimento__r.Id,
                    Unidade__r.Empreendimento__r.Name
                FROM Contrato_Mega__c
                WHERE Conta__c =: contaId
                GROUP BY 
                    Unidade__r.Empreendimento__r.Id, 
                    Unidade__r.Empreendimento__r.Name
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}