force-app/main/default/objects/dfsle__Recipient__c/dfsle__Recipient__c.object-meta.xml
<CustomObject>
    <description>DocuSign Envelope Recipient</description>
    <label>DocuSign Envelope Recipient</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DocuSign Envelope Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/dfsle__Recipient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status do Destinatário</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
                <default>true</default>
                <label>Pendente</label>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evento_de_Envelope__c/Evento_de_Envelope__c.object-meta.xml
<CustomObject>
    <label>Evento de Envelope</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número do Evento de Envelope</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eventos de Envelope</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evento_de_Envelope__c/fields/DocuSign_Envelope__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DocuSign Envelope</label>
    <referenceTo>dfsle__Envelope__c</referenceTo>
    <relationshipLabel>Eventos de Envelope</relationshipLabel>
    <relationshipName>Eventos_de_Envelope</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evento_de_Envelope__c/fields/eventData__c.field-meta.xml
<CustomField>
    <fullName>eventData__c</fullName>
    <label>Dados do Evento</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Evento_de_Envelope__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_de_Envelope__c/fields/sourceId__c.field-meta.xml
<CustomField>
    <fullName>sourceId__c</fullName>
    <label>ID do Objeto Fonte</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Evento_de_Envelope__c/fields/sourceObject__c.field-meta.xml
<CustomField>
    <fullName>sourceObject__c</fullName>
    <label>Nome do Objeto Fonte</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocuSignWebhook.cls
@RestResource(urlMapping='/DocuSignWebhook/*')
global class DocuSignWebhook {
    @HttpPost
    global static void handlePost() {
        String requestBody = RestContext.request.requestBody.toString();
        RestResponse res = RestContext.response;

        // Se o objeto RestResponse for nulo, nós o inicializamos
        if(res == null){
            res = new RestResponse();
            RestContext.response = res;
        }

        try {
            Map<String, Object> requestBodyMap = (Map<String, Object>) JSON.deserializeUntyped(requestBody);

            String envelopeId = (String)((Map<String, Object>)requestBodyMap.get('data')).get('envelopeId');
            dfsle__Envelope__c envelope = [
                SELECT 
                    Id, 
                    dfsle__SourceId__c, 
                    dfsle__DocuSignId__c 
                FROM dfsle__Envelope__c 
                WHERE dfsle__DocuSignId__c =:envelopeId 
                LIMIT 1
            ];

            if (envelope == null) {
                res.statusCode = 200;
                res.responseBody = Blob.valueOf('{"mensagem":"Envelope não encontrado"}');
                return;
            }

            Id sourceId = Id.valueOf(envelope.dfsle__SourceId__c);
            String objectName = sourceId.getSObjectType().getDescribe().getName();

            Evento_de_Envelope__c evento = new Evento_de_Envelope__c(
                Nome__c = (String)requestBodyMap.get('event'),
                DocuSign_Envelope__c = envelope.Id,
                sourceId__c = (String) sourceId,
                sourceObject__c = objectName,
                eventData__c = String.valueOf(requestBodyMap.get('data'))
            );

            insert evento;

            if((String)requestBodyMap.get('event') == 'recipient-completed') {
                Map<String, Object> data = (Map<String, Object>)requestBodyMap.get('data');
                dfsle__Recipient__c recipient = [
                    SELECT 
                        Id, 
                        dfsle__SourceId__c, 
                        dfsle__EnvelopeRecipientId__c 
                    FROM dfsle__Recipient__c 
                    WHERE 
                        dfsle__Envelope__c =:envelope.Id AND
                        dfsle__EnvelopeRecipientId__c =:(String)data.get('recipientId')
                    LIMIT 1
                ];

                recipient.Status__c = 'Concluído';
                update recipient;
            }

            res.statusCode = 201;
            res.responseBody = Blob.valueOf('{"mensagem":"Evento criado com sucesso!"}');
            
            return;
        } catch (Exception e) {
            System.debug(e);
            res.statusCode = 400;
            res.responseBody = Blob.valueOf('{"mensagem":"'+ e.getMessage() +'"}');
            
            return;
        }
    }
}